"""Reports service \u2014 mock backend for analytics data."""

def generate_dashboard_metrics(team_id: str) -> dict:
    # In a real application, these would be generated by executing
    # complex SQL queries (e.g., GROUP BY status, date truncs) against
    # the leads, contacts, and deals tables.
    
    return {
        "kpis": {
            "totalRevenue": 142500,
            "activeDeals": 12,
            "winRate": 68.5,
            "newLeads": 45
        },
        "revenueTrend": [
            {"month": "Jan", "revenue": 45000, "target": 50000},
            {"month": "Feb", "revenue": 52000, "target": 50000},
            {"month": "Mar", "revenue": 48000, "target": 55000},
            {"month": "Apr", "revenue": 61000, "target": 55000},
            {"month": "May", "revenue": 65000, "target": 60000},
            {"month": "Jun", "revenue": 72000, "target": 60000}
        ],
        "leadsByStatus": [
            {"name": "New", "value": 35},
            {"name": "Contacted", "value": 25},
            {"name": "Qualified", "value": 20},
            {"name": "Lost", "value": 10}
        ],
        "pipeline": [
            {"stage": "Lead", "count": 25, "value": 125000},
            {"stage": "Contact Made", "count": 18, "value": 90000},
            {"stage": "Proposal", "count": 12, "value": 85000},
            {"stage": "Negotiation", "count": 8, "value": 65000},
            {"stage": "Closed Won", "count": 15, "value": 142500}
        ]
    }
